Use OS definition of c_char (#8)
c_char being u8 or i8 ends up being kind of os/arch dependent. We
shouldn't hardcode one or the other, we should ultimately depend on what
the C includes tell us is true.

Fixes the following bug on Linux ARM64:
```
error[E0308]: mismatched types
   --> /home/raven/.cargo/git/checkouts/decklink-rs-1ef0154a09905a18/c09af27/src/lib.rs:378:59
    |
378 |                     let ret = Ok(std::ffi::CStr::from_ptr(buffer_data(v) as *const i8)
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`
```

Testing:
  - I can actuall build it now, on my test vm:
    ```
    [2:31:25  raven@nest:~/workspace/avs-agent]$ gcc -dumpmachine
    aarch64-linux-gnu
    ```